
mod error;
pub mod db;


pub use self::error::{Error, Result};
fn main() -> Result<()> {
    Ok(())
}